spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finaldb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: andy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8099

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl