spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finaldb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: andy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8099